events {}

http {
  server {
    listen 80;

    location /api/auth/ {
      proxy_pass http://auth-service:3001/auth/;
    }

    location /api/sensors/ {
      proxy_pass http://sensor-service:3002/sensors/;
    }

    location /api/measures/ {
      proxy_pass http://measure-service:3003/measures/;
    }

    location / {
      proxy_pass http://frontend:3000/;
    }
  }
}